### ISSUE TITLE
DeploymentUnitProcessingException: JBAS011054: Could not find default constructor

### ISSUE THREAD

**Issue by simonjenga** [simonjenga/ListCityATMs#24]
```
13:43:56,557 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: JBoss AS 7.1.0.Final "Thunder" started in 11559ms - Started 134 of 205 services (70 services are passive or on-demand)
13:44:06,432 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) JBAS015876: Starting deployment of "ListCityATM.war"
13:44:10,535 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) Class Path entry jaxb-api.jar in "/C:/jboss-as-7.1.0.Final/bin/content/ListCityATM.war/WEB-INF/lib/jaxb-core-2.2.11.jar"  does not point to a valid jar for a Class-Path reference.
13:44:10,535 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) Class Path entry jaxb-core.jar in "/C:/jboss-as-7.1.0.Final/bin/content/ListCityATM.war/WEB-INF/lib/jaxb-impl-2.2.11.jar"  does not point to a valid jar for a Class-Path reference.
13:44:11,003 WARN  [org.jboss.as.ee] (MSC service thread 1-4) JBAS011006: Not installing optional component org.springframework.web.context.request.async.StandardServletAsyncWebRequest due to exception: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS011054: Could not find default constructor for class org.springframework.web.context.request.async.StandardServletAsyncWebRequest
        at org.jboss.as.ee.component.ComponentDescription$DefaultComponentConfigurator.configure(ComponentDescription.java:606)
        at org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:81)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:113) [jboss-as-server-7.1.0.Final.jar:7.1.0.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]

13:44:11,019 WARN  [org.jboss.as.ee] (MSC service thread 1-4) JBAS011006: Not installing optional component org.springframework.http.server.ServletServerHttpAsyncRequestControl due to exception: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS011054: Could not find default constructor for class org.springframework.http.server.ServletServerHttpAsyncRequestControl
        at org.jboss.as.ee.component.ComponentDescription$DefaultComponentConfigurator.configure(ComponentDescription.java:606)
        at org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:81)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:113) [jboss-as-server-7.1.0.Final.jar:7.1.0.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]

13:44:11,299 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-4) JBAS010404: Deploying non-JDBC-compliant driver class com.mysql.jdbc.Driver (version 5.1)
13:44:11,346 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/ListCityATM]] (MSC service thread 1-7) No Spring WebApplicationInitializer types detected on classpath
13:44:11,377 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/ListCityATM]] (MSC service thread 1-7) Initializing Spring root WebApplicationContext
13:44:11,377 INFO  [org.springframework.web.context.ContextLoader] (MSC service thread 1-7) Root WebApplicationContext: initialization started
```

**Comment by simonjenga** [comment]
https://stackoverflow.com/questions/13786685/spring3-2-and-jboss-as-7

```../jboss-as-7.1.0.Final/standalone/configuration/standalone.xml```

Edit the file with the below filter:
```
<filter>
    <not>
        <match pattern="JBAS011054|JBAS011006"/>
    </not>
</filter>
```
